### ISSUE TITLE
Interactive App

### ISSUE THREAD

**Issue by WesleyTheGeolien** [mycarta/t21-hack-footprint#3]
Using tools like Panel it may be possible to create an interactive app to create a visualise the results of at the filter before applying it to all levels

**Comment by WesleyTheGeolien** [comment]
Interactive tools like [this](https://cerege-cl.github.io/Notebooks-Gallery/notebooks/Retreive_coordinates.html) could be used to draw on top of the image what we want to filter

**Comment by mycarta** [comment]
Starting on a minimum version of the dream below:
![Screen Shot 2021-04-18 at 9 17 38 AM](https://user-images.githubusercontent.com/7424763/115150738-eec4ac00-a026-11eb-8ace-03966beaa3ec.png)
